name: test-environment
channels:
  - conda-forge
dependencies:
  - xarray
  - dask
  - distributed
  - toolz
  - Cython
  - sphinx
  - cartopy
  - matplotlib
  - scipy
  - pyyaml
  - coveralls
  - coverage
  - codecov
  - behave
  - netcdf4
  - h5py
  - h5netcdf
  - pyhdf
  - zarr
  - mock
  - pytest
  - pytest-cov
  - appdirs
  - pip
  - pip:
    - trollsift
